name = "OkRegistrator"
uuid = "5eb89c91-2e2f-4632-ba7c-3ec58ab78207"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.0.1"

[deps]
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
LocalRegistry = "0.5.3"
julia = "1.8"

[extras]
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "CompatHelperLocal"]
